spring:
  application:
    name: loan-approval
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myDB;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  liquibase:
    enabled: true
    user: sa
    password:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /console
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: demo
  filter:
    create: All tasks